title: Portfolio # name of the site
author: Grace Nunnelley # name of site's author
url: https://gnunnelley.github.io
baseurl: /portfolio
# https://mademistakes.com/mastering-jekyll/site-url-baseurl/ 
# url: http://github.com/riggraz/no-style-please # root address of the site
description: > # description of the site (multiple lines allowed)

# favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# sass:
  # style: :compressed

# theme: no-style-please # if you are using GitHub Pages, change it to 
# remote_theme: "riggraz/no-style-please"

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: " ☜(°▽°)" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pdf-embed

# https://jekyllrb.com/docs/static-files/
defaults:
  - scope:
      path: "assets/pdfs"
    values:
      pdf: true

# ps aux | grep jekyll
# port: 4427

